function [featureValues, featureNames] = catchaMouse16_all(data)

featureNames = ...
    { ...
    'SY_DriftingMean50_min'...
    'DN_RemovePoints_absclose_05_ac2rat'...
    'AC_nl_036'...
    'AC_nl_112'...
    'ST_LocalExtrema_n100_diffmaxabsmin'...
    'CO_TranslateShape_circle_35_pts_statav4_m'...
    'CO_TranslateShape_circle_35_pts_std'...
    'SC_FluctAnal_2_dfa_50_2_logi_r2_se2'...
    'IN_AutoMutualInfoStats_diff_20_gaussian_ami8'...
    'PH_Walker_momentum_5_w_momentumzcross'...
    'PH_Walker_biasprop_05_01_sw_meanabsdiff'...
    'FC_LoopLocalSimple_mean_stderr_chn'...
    'CO_HistogramAMI_even_10_3'...
    'CO_HistogramAMI_even_2_3'...
    'AC_nl_035'...
    'CO_AddNoise_1_even_10_ami_at_10'...
    };

featureValues = zeros(length(featureNames),1);
for featureInd = 1:length(featureNames)

    featureName = featureNames{featureInd};

    fh = str2func(['catchaMouse16_', featureName]);

    featureValues(featureInd) = fh(data');

end
    
end